// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID             string
	ExternalID     sql.NullString
	Name           string
	AccountType    string
	CurrentBalance float64
	LastUpdated    time.Time
	RegisteredOn   time.Time
}
