// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Account struct {
	ID             string
	ExternalID     sql.NullString
	Name           string
	AccountType    string
	CurrentBalance float64
	LastUpdated    time.Time
	RegisteredOn   time.Time
}

type Transaction struct {
	ID                string
	AccountID         string
	Amount            float64
	Description       sql.NullString
	Metadata          json.RawMessage
	Tags              sql.NullString
	IsOffset          bool
	IsDeleted         bool
	DateOfTransaction time.Time
	UpdatedAt         time.Time
}
