// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, external_id, name, account_type, current_balance)
VALUES (?, ?, ?, ?, ?) RETURNING id, external_id, name, account_type, current_balance, last_updated, registered_on
`

type CreateAccountParams struct {
	ID             string
	ExternalID     sql.NullString
	Name           string
	AccountType    string
	CurrentBalance float64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.ExternalID,
		arg.Name,
		arg.AccountType,
		arg.CurrentBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.AccountType,
		&i.CurrentBalance,
		&i.LastUpdated,
		&i.RegisteredOn,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, external_id, name, account_type, current_balance, last_updated, registered_on
FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.AccountType,
		&i.CurrentBalance,
		&i.LastUpdated,
		&i.RegisteredOn,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, external_id, name, account_type, current_balance, last_updated, registered_on
FROM accounts
ORDER BY name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.AccountType,
			&i.CurrentBalance,
			&i.LastUpdated,
			&i.RegisteredOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = ?,
    account_type = ?,
    last_updated = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, external_id, name, account_type, current_balance, last_updated, registered_on
`

type UpdateAccountParams struct {
	Name        string
	AccountType string
	ID          string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.Name, arg.AccountType, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.AccountType,
		&i.CurrentBalance,
		&i.LastUpdated,
		&i.RegisteredOn,
	)
	return i, err
}

const updateCurrentBalance = `-- name: UpdateCurrentBalance :one
UPDATE accounts
SET current_balance = ?,
    last_updated = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, external_id, name, account_type, current_balance, last_updated, registered_on
`

type UpdateCurrentBalanceParams struct {
	CurrentBalance float64
	ID             string
}

func (q *Queries) UpdateCurrentBalance(ctx context.Context, arg UpdateCurrentBalanceParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateCurrentBalance, arg.CurrentBalance, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.AccountType,
		&i.CurrentBalance,
		&i.LastUpdated,
		&i.RegisteredOn,
	)
	return i, err
}
