// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, external_id, name, account_type, current_balance)
VALUES (?, ?, ?, ?, ?) RETURNING id, external_id, name, account_type, current_balance, last_updated, registered_on
`

type CreateAccountParams struct {
	ID             string
	ExternalID     sql.NullString
	Name           string
	AccountType    string
	CurrentBalance float64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.ExternalID,
		arg.Name,
		arg.AccountType,
		arg.CurrentBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.AccountType,
		&i.CurrentBalance,
		&i.LastUpdated,
		&i.RegisteredOn,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, account_id, amount, description, metadata, tags, is_offset, date_of_transaction)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, account_id, amount, description, metadata, tags, is_offset, is_deleted, date_of_transaction, updated_at
`

type CreateTransactionParams struct {
	ID                string
	AccountID         string
	Amount            float64
	Description       sql.NullString
	Metadata          json.RawMessage
	Tags              sql.NullString
	IsOffset          bool
	DateOfTransaction time.Time
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Description,
		arg.Metadata,
		arg.Tags,
		arg.IsOffset,
		arg.DateOfTransaction,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Description,
		&i.Metadata,
		&i.Tags,
		&i.IsOffset,
		&i.IsDeleted,
		&i.DateOfTransaction,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, external_id, name, account_type, current_balance, last_updated, registered_on
FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.AccountType,
		&i.CurrentBalance,
		&i.LastUpdated,
		&i.RegisteredOn,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, account_id, amount, description, metadata, tags, is_offset, date_of_transaction, updated_at
FROM transactions
WHERE id = ?
`

type GetTransactionRow struct {
	ID                string
	AccountID         string
	Amount            float64
	Description       sql.NullString
	Metadata          json.RawMessage
	Tags              sql.NullString
	IsOffset          bool
	DateOfTransaction time.Time
	UpdatedAt         time.Time
}

func (q *Queries) GetTransaction(ctx context.Context, id string) (GetTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Description,
		&i.Metadata,
		&i.Tags,
		&i.IsOffset,
		&i.DateOfTransaction,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, account_id, amount, description, metadata, tags, is_offset, date_of_transaction, updated_at
FROM transactions
WHERE account_id = ?
ORDER BY date_of_transaction DESC
LIMIT ?
`

type ListTransactionsByAccountParams struct {
	AccountID string
	Limit     int64
}

type ListTransactionsByAccountRow struct {
	ID                string
	AccountID         string
	Amount            float64
	Description       sql.NullString
	Metadata          json.RawMessage
	Tags              sql.NullString
	IsOffset          bool
	DateOfTransaction time.Time
	UpdatedAt         time.Time
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]ListTransactionsByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByAccount, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByAccountRow
	for rows.Next() {
		var i ListTransactionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Description,
			&i.Metadata,
			&i.Tags,
			&i.IsOffset,
			&i.DateOfTransaction,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = ?,
    account_type = ?,
    last_updated = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, external_id, name, account_type, current_balance, last_updated, registered_on
`

type UpdateAccountParams struct {
	Name        string
	AccountType string
	ID          string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.Name, arg.AccountType, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.AccountType,
		&i.CurrentBalance,
		&i.LastUpdated,
		&i.RegisteredOn,
	)
	return i, err
}

const updateCurrentBalance = `-- name: UpdateCurrentBalance :one
UPDATE accounts
SET current_balance = ?,
    last_updated = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, external_id, name, account_type, current_balance, last_updated, registered_on
`

type UpdateCurrentBalanceParams struct {
	CurrentBalance float64
	ID             string
}

func (q *Queries) UpdateCurrentBalance(ctx context.Context, arg UpdateCurrentBalanceParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateCurrentBalance, arg.CurrentBalance, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.AccountType,
		&i.CurrentBalance,
		&i.LastUpdated,
		&i.RegisteredOn,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET description = ?,
    metadata = ?,
    tags = ?,
    is_offset = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, account_id, amount, description, metadata, tags, is_offset, is_deleted, date_of_transaction, updated_at
`

type UpdateTransactionParams struct {
	Description sql.NullString
	Metadata    json.RawMessage
	Tags        sql.NullString
	IsOffset    bool
	ID          string
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.Description,
		arg.Metadata,
		arg.Tags,
		arg.IsOffset,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Description,
		&i.Metadata,
		&i.Tags,
		&i.IsOffset,
		&i.IsDeleted,
		&i.DateOfTransaction,
		&i.UpdatedAt,
	)
	return i, err
}
